### ISSUE TITLE
Improve request

### ISSUE THREAD

**Issue by michaeledi** [riyadhalnur/user-avatar-wp#3]
Hi!
I really appreciate your code for displaying the avatar in shortcode, but I believe it will be better if we can add a "user id" parameter to display certain user's avatar by typing the userid? Maybe like [display-user-avartar user_id="1" ]?
Many thanks!
Edi

**Comment by riyadhalnur** [comment]
Hi Edi. Thank you for the kind words. It really does mean a lot. I think your request sounds great! This is definitely something that would nice to have. If you want to make a pull request for it, then please send one my way. If not, I'll hook it up once I get a bit of time. Cheers.

**Comment by michaeledi** [comment]
Hi riyadh, I think I've alreay solved this problem, thanks for your inspiration!
